displayName: GeoIP2 Plugin
type: middleware

import: github.com/negasus/traefik-plugin-geoip2

summary: '[GeoIP2] Add Country Header'

testData:
  FromHeader: 'X-Real-IP'
  CountryHeader: 'X-Country'
  Filename: 'GeoLite2-Country.mmdb'